### ISSUE TITLE
redefined message needs an extra space

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#132]
I got some blocks words working!  It looks like:
```
2 list 
Screen #   2
 0 : ( Simple editor for screens/blocks )                            
 1 : decimal                                                         
 2 : : L  ( -- )                                                     
 3 :     scr @ block              ( Load the screen )                
 4 :     cr ." Screen #" scr @ 4 u.r  ( Print the screen number )    
 5 :     16 0 do                                                     
 6 :         cr i 2 u.r ."  : "   ( Print the line number )          
 7 :         dup i 64 * + 64 type ( Print the line )                 
 8 :     loop cr drop ;                                              
 9 :                                                                 
10 : : list  ( scr# -- )                                             
11 :     scr ! ( Save the screen number)                             
12 :     L ;       ( Print the screen )                              
13 :                                                                 
14 :                                                                 
15 :                                                                 
 ok
2 load redefined lredefined list ok
```
The only annoying part is the warning messages about redefining words run together.    I'm thinking an extra space at the beginning is probably going to be easier than one at the end, because you print the word name at the end.

**Comment by scotws** [comment]
Interesting problem, because normally would never see that because it's pretty much impossible to redefine one word in a single go. I note that Gforth has the "ok" pretty far away from the word printed, which makes it seem the space is being after the offending word. Maybe add a space by hand as well after line 6644?

One other thing, the column of colons next to the word seems a bit hard to read to me when you have a definition. As far as I can tell with a simple **2 list** on Gforth, there are no colons printed at the beginning of the word. Maybe a pipe instead of colons? Or just nothing at all?

**Comment by SamCoVT** [comment]
I agree that colon was not a good choice for a separator.  I'll play around with that and see if another character looks better.  If not, I'll just leave a gap.  The numbers are already right justified, so a gap may be fine.
