### ISSUE TITLE
Code temporary high-level words natively

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#14]
Exampe: **WITHIN**. Note we want to make sure we have test cases for these words before we code them in assembler. **TO** is another candidate.

**Comment by scotws** [comment]
**/**, **/MOD** and **MOD** probably can be combined to good effect in assembler; currently, **/** and **/MOD** share most of their code.

**Comment by scotws** [comment]
I've started working on **ENVIRONMENT?** because I'm rebuilding some of the string stuff anyway

**Comment by scotws** [comment]
With **ENVIRONMENT?** done, **SEE** might given the next big savings.

**Comment by SamCoVT** [comment]
**ENVIRONMENT?** looks good, and it gets rid of **STRING_OF** in the dictionary.  Also, thanks for catching that MAX-CHAR error.  That's what happens when the same programmer makes the code and the tests for it :)  I was way off base (my bad pun for the day).

**Comment by scotws** [comment]
Groan :-)

**Comment by scotws** [comment]
**HEXSTORE** should be converted to assembler as well.

**Comment by scotws** [comment]
I'll take a look at **see** and **hexstore** next.

**Comment by scotws** [comment]
So we only have **.wid** (currently 252 bytes) and **order** (130 bytes) left (yay!) I'll try to get to the last underflow stuff tonight (German time). Not sure how much I'm going to be able to do from Saturday one, I'd sit down and try to clean up that mess around **cleave** next.

**Comment by scotws** [comment]
**cleave** is done. Unless you are already on them, shall I take a look at **.wid** and **order**?

**Comment by SamCoVT** [comment]
You are welcome to attack `order`.  The word `.wid` was just a helper word, and doesn't need its own word in the dictionary - it can be merged directly into order.  It will also give you some experience playing with the search order directly.

You can look at the top of `xt_find_name:` to see an example of traversing the wordlist order.  You can take a look at `xt_get_current:` for an example of how to get the current wordlist id.  My only warning is that `TYPE` uses tmp1, but the other two temps are available - you'll probably be bypassing TYPE anyway, at the assembly level, so that probably won't be an issue for you.

I believe everything you need to touch will be byte variables, as you don't actually need the dictionary pointers themselves.  That will also help verify if the documentation in definitions.asm is adequate for the search order.

While you are in there, you may want to consider if we want to consider adding the words `EDITOR` and `ASSEMBLER` to make things like `ONLY FORTH ALSO ASSEMBLER` work out of the box. That is an older method of handling the search order, and we can already say things like `ASSEMBLER-WORDLIST >ORDER` now, so it may not be as big a deal.
