### ISSUE TITLE
Rewrite disassembler to save space and add features

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#153]
The built-in disassembler currently only prints the address and the instructions. On the same line, it should print the hex machine code of the instructions as well. This is low-priority.

**Comment by scotws** [comment]
Rewrite should output code in SAN postfix notation (`1000 sta`) so we can copy and paste from the disassembler to the assembler. 

Also, rework the table with mnemonics and lengths so we use less space: Each entry starts with one "length byte" with bits 0 and 1 coding for the number of bytes of the instruction (1 to 3) and bits 2 to 4 for the length of the string (3 to 7 chars such as `lda.zxi`). Bits 5, 6, and 7 are unused. The strings are then not zero-terminated, saving more space.

At this point, the assembler routines can be simplified, removing the `ldy.#` instruction from every assembler word routine, and getting the length from the mnemonic table as well, saving further space.

**Comment by SamCoVT** [comment]
I'm not sure if it's useful in your code, but you may want to consider using bits 6 and 7 for the length bits because bit 7 can be tested (using bpl/bmi) right after an lda, and both bit 7 and bit 6 can be tested after a BIT instruction (using bvc/bvs for bit6).  I would do 1-byte intructions as 00 (or 01), two byte instructions as 10, and three byte instructions as 11 to make the most efficient bit test path.  That makes bit 7 say if it takes an argument, and bit 6 say if it's a byte or 16-bit argument.

You can then move the char count down to the lower bits, allowing you to just use an AND mask to get the count directly instead of having to shift them (or use subtraction to count down in-place).

**Comment by scotws** [comment]
Yep, basically, this what happens. The disassembler is now 1.8 KB in size after something over 2 KB, so we did save some space. Let me know if this works for you with cut and paste. 

Hopefully, I'll get to rewriting the assembler to use the new tables today or probably tomorrow as well.
