### ISSUE TITLE
Suggestion: How to position the two default editors

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#156]
Amazingly enough, I'm finally making some serious progress on the line-based editor. Though it is still going to take a while (I'm beginning to hate linked lists in assembler), this might be a time to talk about what direction the two editors we're going to have - ed and then the block-based one @SamCoVT has done first work for - so they don't overlap.

As a first suggestion: 

- We make "ed6502" a simple, small **pure-ASCII based** editor that can be used over any connection to Tali. My strange fixation with line-based editors aside (I'm sure there is an entry in DSM-V for that somewhere), hardly anybody is going to use it for more than the simplest things. We get it running, get it stable, create tests, create docs, freeze it, and that's it. It's always there if things go sideways.
- In contrast, we make the "block" editor pretty and with bells and whistles and cool features. I'm wondering if it would be defensible to make it **ANSI-terminal required** - isn't that the most common way people will be interfacing with Tali? - and even support (gasp) bold text and color. One way or the other, it would be the main, recommended, primary editor.

That's just a suggestion, I might be misjudging usage cases here?

**Comment by SamCoVT** [comment]
I just recently discovered that Tali has `at-xy` implemented, and it works!

For my uses, I don't need a fancy block editor.  In fact, I really only got as far as erasing a line, erasing a screen, entering a line, and entering a screen.  Most of the time I use the "enter a screen" method and just paste my code from my editor on the PC.  I've been super happy since I added hardware (RTS/CTS) handshaking and interrupt driven receive so I can do that without losing any characters.

I'd be happy with a simple line editor and a simple block editor.

**Comment by scotws** [comment]
Saw your issue with that on py65, I think we're doing things with the emulator they had never planned :-). Okay, I'll finish my editor and then we can figure out what to do with the block editor later. 

(What I couldn't figure out is how to implement **GET-XY**, which would allow lots of fun tricks as well. It's in the *Forth Programmer's Handbook* as "common usage", but not in Gforth or ANSI.)

**Comment by SamCoVT** [comment]
The issue I opened over on the py65 project is actually just when running the emulator straight, and I run into it when pasting code I want to test (especially for debugging) into the terminal running py65mon.  

The modifications we made for the tester actually work around this problem by replacing the input and output routines entirely.  That was the reason we needed the newest version of py65mon for a while (but now can just use the version installed with pip) -- it was the first that had the ability to replace the input and output routines accessed by the OS (or in our case Forth) running in the emulator.  Now that most of the bugs have been shaken out of it, the tester has actually been really solid and hasn't had any issues with lost characters or delays.

I can probably code GET-XY for you.  There is an ANSI code you can send to a terminal and it will automatically respond with the current cursor position.  I only know this because I used to run a BBS a long time ago, and this was how you could tell if someone's dial-up software supported ANSI or not.  The BBS software would send this special code, and if a response came back, it would turn on ANSI (because everything is better in color, including login prompts!)  If no response came back, it would fall back to plain ASCII.  I never used the cursor position information - I just used the response (or lack of response) in a given time (about half a second, if I recall) to tell if I could send ANSI sequences or not.

Wikipedia's article on ANSI escape sequences seems to think the magic sequence is `ESC[6n` where ESC is ascii code 27.  The terminal will respond with `ESC[n;mR` where n and m will be the row and column respectively (and may be multiple digits long for large screens).  A quick test (because Forth makes it so amazingly easy to test things quickly) shows that this works:
```
: ESC 27 emit ;  ok
: querypos esc ." [6n" ;  ok
: getpos querypos begin key dup 27 <> if dup emit then [char] R = until ;  ok
getpos [40;8R ok
getpos [41;8R ok
   getpos [42;11R ok
```
A little bit of parsing (they will always be in decimal) and you will have your **GET-XY**

PS.  I'm super excited that I was able to write that loop and if without having to look anything up!  After a while, you just start _thinking_ in Forth (for small snippets of code, anyway.)

PPS.  I've now run into several instances where I'd like to put special characters in strings - I think `S\"` might be worth implementing.

**Comment by scotws** [comment]
**S\\"** sounds great if you say you need it. The way I see it we go flat-out on whatever we think is a good idea until we run out of ROM, then we go back and figure out how to make things more compact. 

Congrats on the loop! I remember thinking that I'll never understand **if**, let alone **do**, and **defer** was completely beyond me. Now I find myself thinking "I should use defer for this" when programming in Python. 

(When you get to missing the "wait, what?" feeling of learning Forth, I can suggest Haskell -- the son of a school buddy of mine is learning it, and suggested I spend some time with it. Half of the time, I have no idea what they are talking about, and I haven't even hit the infamous "monad" yet. My current theory is that it was actually developed by aliens, and the whole "functional programming" thing is some thin goverment cover story...)

Anyway, editors. I'll close this, and see how complex we want the block editor later.
