### ISSUE TITLE
Add test suite for ed

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#159]
Before we add more features and start to fool around with refractoring what is a horrible mess of code, we need a test suite for ed to make sure we don't break anything, as fragile as the whole thing is.

**Comment by scotws** [comment]
Ignore the last test, it isn't really doing what I thought it was.

**Comment by scotws** [comment]
So this is going to be more complicated than I thought. The problem is that once we start **ed**, we leave the world of Forth testing where we can compare what's on the TOS with what we expect it to be. 

What we need to do instead is compare the direct `stdout` with what we expected `stdout` to show. If I understand this correctly, that means we have to modify talitest.py (revector `putc_results()`?) to there is what I'm calling "direct mode". In pseudo-Python, the whole thing would be something like
```
# commands and responses, probably from ed.fs though
ed_tests = [ ("ed", ""), ("d", "?"), ("q", "")] 

for cmd,want in ed_tests:
    got = send_to_tali_somehow(cmd)

    if got != want:
        print("Error with {0}: Got {1}, wanted {2}".format(cmd, got, want))
```
Or something to that effect. We don't to do that all the time, of course. My current ideas are either to define a word in `tester.fs` that switches to "direct mode" until switched off again, or possibly create a Forth word that switches just to DM for this comparison. Since this is mostly going to be **ed** for the moment (though we could probably use something like this to test other words such as **dump**), the mode version sounds easier to use.

Since you're involved with all kinds of input/output stuff at the moment, and know more about how this all interfaces with py65, I don't want to touch any of this without talking to you - also, there might be a better way I'm not seeing?

**Comment by SamCoVT** [comment]
Here is my proof-of-concept that works in the simulator and on my hardware.  I also found an interesting bug where the redirected output code can't use any words that use TMP1 because `TYPE` uses it and it messes up the output.  I was using `+!`, for example, but had to switch to doing it manually (and check that none of the simpler words touched TMP1).  I don't know if it's worth pushing/popping tmp1 in `TYPE` or not, but it's worth thinking about if the redirection code is written in Forth.

```
\ PROGRAMMER  : Sam Colwell
\ FILE        : redirect.fs
\ DATE        : 2018-11-03
\ DESCRIPTION : Routines to redirect output into a string.

variable 'oldout
variable #saved-output
create 'saved-output 1000 allot

: saved-string ( -- addur u )   'saved-output #saved-output @ ;

hex
: save-output  ( c -- )
    \ Get value in A onto stack
    [
    CA c,       \ dex
    CA c,       \ dex
    95 c, 00 c, \ sta 0,x
    74 c, 01 c, \ stz 1,x
    ]
    
    saved-string + c!
    \ Note: Can't used +! as it uses tmp1 and so does TYPE
    #saved-output @ 1+ #saved-output ! ;

: redirect-output ( -- )
    output @ 'oldout !        \ Save the original vector.
    ['] save-output output !  \ Replace the vector with our routine.
    0 #saved-output ! ;       \ Empty the string to start.
: restore-output ( -- ) 'oldout @ output ! ;

\ Simple test
decimal
: test redirect-output ." Test words that output here" restore-output ;
test
cr s" It said: " type saved-string type cr
```

**Comment by scotws** [comment]
Ah, thanks for that, I'll see about building a test file around that the coming days (I'm going to be busier than usual for the next ten or so days). I keep forgetting about real hardware, you're right that we definitely want to have testing work on there as much as possible.

**Comment by scotws** [comment]
@SamCoVT I can't seem to find a way to run the advanced tests for `ed`, though your redirection code is working perfectly. After playing around with various variants I think the basic problem is that `ed` uses `refill` (of course), but that by design doesn't play well with `evaluate`, which has been my best shot so far. I actually coded `execute-parsing` (easier than I thought, actually), but that doesn't help either. I can get `ed` up and running, but no further commands.

Possibly we might have to redirect the input as well. However, we have basic tests in place, and given the number of people who use `ed` currently is exactly 1, I give it one more day of experiments, and then we'll just leave it till sometime in the future.

**Comment by scotws** [comment]
Yeah, so this is not working right now, and this is not the best use of my time, I think. I'll keep this in the back of my head and leave the redirect code in the test file for now.

**Comment by SamCoVT** [comment]
I'm a little curious... can you give me an explanation of what you're trying to do?
I see the redirection setup in **ed.fs**, but I don't see what you're trying to test in ed.

You mention evaluate, and conflicting with refill, so that makes me think you are trying to use evaluate to somehow feed `ed` from a string.  I think that's too complicated...  Remember that the test program is already spoon feeding Tali the input, character by character, from the ed.fs file.  Even though the output is redirected (and therefore not immediately visible), the input still works just like it did before.  Anything that you can type into the simulator you can just put into the ed.fs file (including quitting ed and running `restore-output` to stop the logging to the string).  You may have a few extra bits in your results, like the command to restore the output at the end, but it should work and be consistent.  You may need to make your `saved-output` string a little bigger, though.

**Comment by scotws** [comment]
What I would like to be able to do is test the printing words such as `p` or even just `=`. However, I can't figure out a way to even run `ed` directly followed by `q` - the test hangs after `redirect-output`: 
```
redirect-output
ed
q
restore-output
cr saved-string type
```
I have in fact tried various things with `s\"ed\nq\n` and `evaluate` as well, but to no avail. Maybe I am overthinking stuff -- I'd be grateful for any suggestion.

**Comment by scotws** [comment]
Ah, I was looking in the completely wrong place. Thanks! I've included a first `ed q` test, and yes, it now works exactly as you said it would. I'll add a couple more tests, and then we can close this. Nice.
