### ISSUE TITLE
Add Gforth's >ORDER (and possibly others) to the Search Order wordset

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#184]
The current ANS Forth implementation of word lists is rather low-level and slightly confusing at first. We should take **>ORDER ( wid -- )** from Gforth which does the one simple thing people look for first: Push the wordset **wid** on the search order (see https://www.complang.tuwien.ac.at/forth/gforth/Docs-html/Word-Lists.html). We should use this as a base for **EDITOR** and **ASSEMBLER**.

**Comment by SamCoVT** [comment]
That looks like an excellent word.

The wordlist names like FORTH and EDITOR and ASSEMBLER have some odd behavior (which is different than `>ORDER`) that is largely historical and goes back to vocabularies.
The word `FORTH`, for example, _replaces_ the first wordlist in the search order.  I believe the EDITOR and ASSEMBLER words are supposed to be similar, as they will be used with `ALSO`, which has the slightly odd behavior of duplicating the first wordlist in the search order.  It's essentially making a space for FORTH or EDITOR or ASSEMBLER to replace with their own wid.  The idea is to make it so that older code that used the `ONLY FORTH ALSO ASSEMBLER ALSO EDITOR DEFINITIONS` vocabulary method to determine the search order and compilation vocabulary will still work with the new wordlists and search order.

I do think we should add `>ORDER`, but if we base FORTH, EDITOR, and ASSMBLER off of it, we will not be ans-compatible with the word FORTH (the other two are not specified by ANS, but should probably behave similarly).  It's a bit frustrating because I agree with you on how it _should_ work, but the ANS standard is hobbled here by trying to be backwards compatible.
