### ISSUE TITLE
Follow Gforth's format of displaying the ORDER of wordlists

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#186]
The exact display of wordlist **ORDER** is implementation dependent (see https://forth-standard.org/standard/search/ORDER). Since wordlists are complicated enough for beginners, we might see about having Tali's version of the word follow the convention of Gforth (see https://www.complang.tuwien.ac.at/forth/gforth/Docs-html/Word-Lists.html):

> Print the search order and the compilation word list. The word lists are printed in the order in which they are searched (which is reversed with respect to the conventional way of displaying stacks). The compilation word list is displayed last. This gives us for example:
```
Forth Forth Root     Forth  ok
```
though we don't use "Root", just "Forth" at the beginning. This is a low-priority enhancement.

**Comment by SamCoVT** [comment]
It's interesting to see that they have the Forth wordlist listed twice in the search order.  I suspect it's to make reasonable behavior if you use one of the older vocabulary words (like `ASSEMBLER`) is used, so that it has a spot at the beginning of the search order to replace without blowing away Forth.  I didn't see duplicate words listed in the output of `WORDS` (although OMG they have a lot of words!) so they must have a method to list them just once.

We can add the CURRENT (aka compilation) wordlist to the display as well, and I can change the display to use the shorter names , eg. FORTH instead of FORTH-WORDLIST, etc.  I'd like to rewrite the wordlists at some point in the future (for both size and speed), so I can tackle this at that time.

**Comment by scotws** [comment]
Sounds good. I'll add a "leave for now" tag.
