### ISSUE TITLE
Reverse assembler instructions in headers.asm for alphabetical order

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#209]
The assembler words in headers.asm are currently listed in alphabetical order, which made debugging easier. However, they should be listed by how often they are used so that more common words are found faster. 

One possible way of doing this: Take `docs/py65mon-listing` and only keep the second column with the opcode. Count the number of times each opcode occurs. Based on that, reconstruct the assembler part of headers.asm. This is could probably all fit in a one-shot Python script in `tools`.

**Comment by SamCoVT** [comment]
After trying out the assembler, I'll actually recommend leaving them in alphabetical order.  I can do a `words` and then hunt alphabetically for the words starting with "lda" in order to see what addressing modes are available and exactly what the name is.  My only recommendation would be to reverse the order so that `words` lists them in a-z alphabetical order.

**Comment by scotws** [comment]
Fair enough. Will figure out a script to reverse them.
