### ISSUE TITLE
Prepare for Version 1.0

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#229]
So I think that's pretty much all I had wanted to add for Version 1.0, unless I'm forgetting something? We should probably go over the whole thing once for obvious improvements and typos, but the test suite does take an enormous load off this sort of thing.

**Comment by SamCoVT** [comment]
I think it's in pretty good shape.  I don't have anything I want to do that can't wait until post 1.0 release.  I'm looking at cleaning up the test folder next, but that can wait.  I can give it a once-over this evening.

**Comment by SamCoVT** [comment]
I just ran all of the tests (except cycle tests) on my SBC and the only test that failed is the 
`T{ here unused + 3FF + -> 7FFF }T` test, and that one always fails on my hardware because my I/O is mapped into the $7F00-7FFF range and I have some ACIA buffers for interrupt driven serial receive up at the top of ram.  My total RAM that Tali thinks it can use is always a little bit lower.  The number it's reporting ($7DFD as the end of usable RAM) is correct for the SBC hardware.

All of the other tests passed.  This means we are good to go on real hardware for a 1.0 release.

**Comment by scotws** [comment]
Cool! I need to update the copyright stuff, it seems, 2019 and all of that, and then I'll look through the code again if anything jumps at me. Otherwise, I'll put the release together today or tomorrow and tell the forum.
