### ISSUE TITLE
Makefile and Building on Windows needs some work

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#246]
A user on the 6502.org forums mentioned issues building Tali on Windows.  I can confirm there are some issues, including:

There are weird issues with "python3" and the python folks appear to be moving away from this method of differentiating between v2 and v3.  When I downloaded and installed 3.8.1, running `python` at a command prompt got me into a session, but running `python3` brought up the windows store instead (which wants to install an older version).  There is no python3.exe in the windows 3.8.1 distribution.  Perhaps just changing all of the references to `python3` with `python` is finally appropriate.  There also seems to be a "launcher" named `py` that you can use like:
```
py -3 script_that_needs_python3.py
```
This might be the new method the python group is using to fix up the mess they made with python2 vs python3.  Some research to find a cross-platform method of running the scripts with python3 is needed.

Semicolons in commands confuse the windows command prompt.  The semicolon at the end of lines 18 and 24 in the Makefile should be removed to make those commands work in windows as well as linux.

Also just a note, some of the test sources listed in the Makefile are old, and I will update those as well.

**Comment by scotws** [comment]
Thanks for this (I'm half a planet away from the computer with my Tali files for a couple more days). I had never attempted to build Tali on Windows, I must admit, but since two family members have now switched to Win 10 I should be able to set up something where I can test it. -- Before it comes up, we don't have any up-to-date Macs in the house anymore, at least nothing that will run the current macOS versions. 

As for Python -- though it's the first language I really feel in love with, I'm getting increasingly annoyed with the constant changes and all the hand-holding it needs. I'm wondering if would make sense long-term to rewrite the scripts in (say) Go? That might introduce another step (compiling executables), but the nice thing about Go is that they don't fool around with the language all the time and stuff like formatting is automatic. 

Thanks again!
