### ISSUE TITLE
Code for MOVE is flat-out wrong

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#56]
The test for **MOVE** is failing because it is based on **CMOVE** and **CMOVE>**, which both propagate ("clobber") bytes depending on the direction of the move, whereas **MOVE** does not. See https://www.forth.com/starting-forth/10-input-output-operators/ for background on this. -- The code for MOVE must be completely rewritten.

**Comment by SamCoVT** [comment]
It's flat out wrong in that it simply picks the wrong mover (cmove vs cmove>) which guarantees clobbering your data if the areas overlap.  It might be as easy as changing your bcc branches to bcs instead (two places).  I'll look into it further.

**Comment by scotws** [comment]
I'm still getting the test error with the corrected **CMOVE>** test: 

```
{ seebuf -> 12 12 34 } INCORRECT RESULT: { seebuf -> 12 12 34 } ACTUAL RESULT: { 12 12 12 } ok
{ seebuf -> 12 34 34 } INCORRECT RESULT: { seebuf -> 12 34 34 } ACTUAL RESULT: { 12 12 12 } ok
```

If I understand correctly what is supposed to go on, the **CMOVE** and **CMOVE>** are supposed to propagate, and **MOVE** is not, which is what those two lines are testing for.

**Comment by scotws** [comment]
I may be completely lost in the woods here, so let me walk though the way I currently understand the differences between the three words to see where I might be missing something. 
- **CMOVE** and **CMOVE>** are the traditional Forth move words that work on characters (bytes, in our case).  See https://www.forth.com/starting-forth/10-input-output-operators/ for a discussion on the differences between them, which are not really relevant to this discussion.
- **MOVE** is more modern (see https://forth-standard.org/standard/core/MOVE) and works on "address units" (also bytes, in our case)
- If the regions to be moved don't overlap, all three words work exactly the same (at least in our case). The current Tali code works fine in those cases, and everybody is happy.
- If the regions do overlap, **CMOVE** and **CMOVE>**, but not (!) **MOVE**, show a special behavior: They "propagate" or "clobber" the characters. The standard says: "They specify a behavior for moving that implies propagation if the move is suitably invoked." 
- The problem as I see it: Since Tali's **MOVE** currently just calls either **CMOVE** or **CMOVE>**, propagation also occurs with **MOVE**, though it shouldn't.
- The comparison with the behavior of Gforth would seem to support this diagnosis. Both show the same behavior for overlapping **CMOVE**, which is good:
```
create testbuf char a c, char b c, char c c, char d c,  \ -> ok
testbuf 4 type \ -> abcd ok
testbuf dup char+ 3 cmove  \ -> ok ( move three chars over by one char, with propagation)
testbuf 4 type \ -> aaaa ok
```
However, the behavior of **MOVE** is different in this case.  Gforth first:
```
create testbuf2 char a c, char b c, char c c, char d c, \ -> ok
testbuf2 4 type \ -> abcd ok                                
testbuf2 dup char+ 3 move  \ -> ok                          
testbuf2 4 type \ -> aabc ok ( no propagation! )
```
This, however, is Tali's current behavior (first three lines are the same as above):
```
testbuf2 4 type \ -> aaaa ok ( eeek! )
```
Gforth copies three bytes one byte further down, so of the four characters printed, the last three ones are the ones that were moved. Tali just runs **CMOVE**, which includes the traditional propagation behavior, exactly what **MOVE** was created to prevent.

This is why I'm thinking that the code for **MOVE** is simply wrong. When I wrote it, I (obviously) didn't understand about the way propagation works in the cases of overlapping code, and since overlapping regions are so rare, nobody noticed it until now.

If this is correct -- and again, I might be lost in a Forth-est of trees -- we would need two things: Better tests for **CMOVE** and **CMOVE>** (can't seem to find any, but the non-overlapping can just use some of the **MOVE** stuff. and we can use Gforth as the gold standard) and completely new code for **MOVE** that doesn't propagate.

**Comment by SamCoVT** [comment]
You're on the right track.  The propagation is a "failing" of the code to preserve source bytes before they are overwritten as destination bytes, and it only happens with overlapping buffers, like you said.  The important distinction here is _how_ the buffers overlap.  If s and d are source and destination:
```
s    |--------|
d |--------|
Source is higher in memory than destination.
CMOVE will work, CMOVE> will clobber/propagate 
from the right side towards the left once it hits the overlapping portion.
```
```
s |--------|
d    |--------|
Destination is higher in memory than source.
CMOVE> will work, CMOVE will clobber/propagate 
from the left side towards the right once it hits the overlap.
```

In each of these two cases, one of {CMOVE,CMOVE>} will always work correctly (with no clobbering/propagation), while the other will clobber/propagate.  That's why there are two different words that do essentially the same thing.

Tali's current code for MOVE, which compares source and destination pointers and then picks either CMOVE or CMOVE> is on the right track (and is a correct solution for a byte-addressable machine,) but it simply picks the wrong one every time.  Your CMOVE and CMOVE> are both working fine, but MOVE is always picking the one that clobbers when it always wants the one that doesn't clobber.  

If the destination is higher in memory than the source, CMOVE> should be used. You already have a comparison with a branch on carry clear to CMOVE>.  My proposed fix is to simply change it to a branch on carry set to CMOVE> instead.

The propagation tests, by the way, are simply testing CMOVE and CMOVE> on buffers overlapping in the _WRONG_ direction for those words to see if they are copying from the end they are supposed to be - by looking for the "propagation" behavior that in normal operation is undesired.

**Comment by scotws** [comment]
Ah, now I get it. Thanks for the explanation (made slightly more bizarre by the fact that at some point I actually wrote the code, jeeze). I've finally had the chance to download and test it, and it does work perfectly as you predicted. Thx!
