### ISSUE TITLE
Add tests for strings that are longer than 255 chars

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#71]
Because this is an 8-bit MPU, there might be various hidden issues with strings that are indexed in 8-bit (see @SamCoVT discussion while rewriting code for larger than 255 char strings handling in #69).

**Comment by SamCoVT** [comment]
I suppose I should tackle this one.  Strings are kinda hard to deal with, but I can look at the addresses and lengths.  I'm thinking a string with about 250 characters and then 10 spaces on the end might be useful.  That way I can test -TRAILING across a 256 byte boundry.  Are there any other types of tests you think might be useful?

**Comment by scotws** [comment]
Well, it would have to contain tests for all of the major string words - **-TRAILING** etc - and I'm wondering if we should have one test for a *double* crossing of the 256 byte boundry.

**Comment by SamCoVT** [comment]
As you wish.  #81 has a string with enough spaces on the end to cross boundries twice (meaning -trailing will cross them twice in the way back).  Be warned that I had to increase the intercharacter delay on my system to make it run correctly.

**Comment by scotws** [comment]
@SamCoVT Done, but the time the test takes is madness ... how about we comment the long string test out, and you have to run it by hand ; or we create a special list of "long" tests you call with a different parameter (say, ` -l` / `--long`)? Or am a being an wimp, and we just need to accept that the tests take that long?

**Comment by SamCoVT** [comment]
I'm fine with commenting out the long string tests for now.  It's much better (for me) to have the test suite run reasonably quickly so I get faster feedback that I've broken something.

If/when I/you get around to writing a custom py65mon based test program, we'll be able to feed the input to Tali at the exact speed it actually wants it, and this won't be an issue anymore.  py65mon has a hook to run your own function when a particular memory address is read, and that's how the current input is done.  It's just that the function used doesn't work very well for our application.  

Because it will be moot in the future, I wouldn't recommend even bothering with a special command line argument to run them.  I would recommend just moving them to their own test file so you can ask for them by name, and later we will include that test file in the default list.
