### ISSUE TITLE
Create tests for Tali Forth word DIGIT?

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#85]
... which seems to be causing the failure of test gp7-2 - the conversion is affected so X is missing from the character list. This looks suspiciously like a one-off error somewhere.

**Comment by SamCoVT** [comment]
Your issue is in `xt_number_sign` rather than `digit?` and the cause is in strings.asm here:
```
; ALPHABET STRINGS
s_abc_lower: .byte "0123456789abcdefghijklmnopqrstuvwyz"
s_abc_upper: .byte "0123456789ABCDEFGHIJKLMNOPQRSTUVWYZ"
```
I highly recommend adding X to the alphabet. It's much more EXciting that way (insert bad pun groan here.)

FYI: It was the correct number in memory the whole time, but got printed out wrong when `xt_number_sign` (called by `#S`) used the string to convert it for printing.  This was caught in gp7 (yay tests!) because that routine actually looked at the ASCII value of the character returned for each "digit" in base 36.

**Comment by scotws** [comment]
Oh good grief. This is probably not the stupidest bug of my life, but it's sure up there ... I'll still create a test for *DIGIT?*, just because, but that cleared up that bug nicely, thanks. I think I seriously need to get more sleep :-).
