### ISSUE TITLE
Test for CASE fails if (and only if) called with -t core, not with -t all

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#88]
So this is weird. I have been getting flaky failures of the **CASE** test for the number 3 - but _only_ the number 3, and _only_ when talitest.py is called with `-t core` and not `-t all`:
```
{ 3 cs1 -> 333 } INCORRECT RESULT: { 3 cs1 -> 333 } ACTUAL RESULT: { 3 } ok
```
Up till now, I had assumed that this way just a case of dropped characters, but with the new Awesome Test Suite, that can't be it -- if it were to drop anything, it would be the super-long strings.

Note that 3 is the first number that Tali has to run through **>NUMBER** because 0, 1, and 2 are hard-coded for speed. However, swapping the tests for 3 and 4 in `core.fs` makes 4 fail:
```
{ 4 cs1 -> 444 } INCORRECT RESULT: { 4 cs1 -> 444 } ACTUAL RESULT: { 4 } ok
```
If I comment out the tests for 1 and 2, it works again with '-t core' and '-t all'. If I define the **CASE** statement with 3, then go to 1, 2, and then 4, but leaving the test sequence 1, 2, 3, 4, it fails at 2.

So it would seem that I'm failing at what is defined at the third case of, uh, **CASE**. @SamCoVT could you see if you can reproduce any of this?

**Comment by SamCoVT** [comment]
First of all, a handy tip:  Put `bye` just after the test of interest to halt the testing early.  The tester will complain that Tali crashed before the tests were completed (because it didn't get to feed the entire test string data to the emulator), but will still give you the summary up to that point.

Confirmed.  When running with '-t core' I get:
`{ 3 cs1 -> 333 } INCORRECT RESULT: { 3 cs1 -> 333 } ACTUAL RESULT: { 3 } ok`

When I copy the cs1 word definition into a Tali2 session and run the tests (printing the result instead of using the test words), it works fine.
Swapping the lines for 3 and 4 in the case statement (but leaving the tests in order) gives me failure on 4 instead, just like you show.

The interesting part is that the original number is left on the stack, and this case has a default, so that should never happen.

"of" sequence 3 1 2 4 5 6 7 fails on 2 (returning 2), like you described.
"of" sequence 3 4 1 2 5 6 7 works fine.
"of" sequence 1 3 4 2 5 6 7 works fine.
"of" sequence 3 2 1 4 5 6 7 fails on 1
"of" sequence 4 1 5 6 7 2 3 works fine (ruining my hypothesis that it's a 1 or 2 in the second "of")
"of" sequence 4 2 5 6 7 1 3 works fine (confirming my ruined hypothesis)
"of" sequence 2 4 1 5 6 7 3 fails on 1

My new hypothesis is that if 1 and 2 appear any of the first three "of" lines, the third "of" will fail.
Let's try adding 0 to the mix with a `0 of 888 endof` as the first line (but not including any tests for 0/888):

"of" sequence 0 2 4 1 5 6 7 3 works fine :(
"of" sequence 0 1 2 3 4 5 6 7 works fine :(
"of" sequence 0 1 3 2 4 5 6 7 works fine :(

Adding a test for 0 (placed above the test for 1, checking for 888)
"of" sequence 1 2 0 3 4 5 6 7 works fine (unexpected success)
"of" sequence 1 2 3 4 5 6 7 0 fails on 3

I have no hypothesis at the moment.  It seems to deal with 1 and 2 in the first three spots, but 0 is not equivalent to 1 and 2 (in terms of breaking things) even though it's also a defined word.  I suspect a deep dive will be needed, but this one is difficult to reproduce because this case statement works fine when typed in.

**Comment by SamCoVT** [comment]
Trying to find simplest test:
just cases 1 2 and 3 work (default case not needed)
This results in cs1 having an xt size of 246 bytes, which might be small enough to look through.  I do need to figure out how to get it to misbehave when typed into the emulator, though.

Just for fun, I tried:
```
: cs1 case 
   5 4 - of 111 endof
   6 4 - of 222 endof
   7 4 - of 333 endof
   endcase
;
```
and it passes the first three tests!  This seems to confirm that it is some kind of interaction between the hardcoded words for 1 and 2 and the case words.
